services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - published: 5432
        target: 5432
        protocol: tcp
        mode: host
    volumes:
      - postgres_data_container:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - published: 27017
        target: 27017
        protocol: tcp
        mode: host
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend
    configs:
      - source: init_mongo_script
        target: /docker-entrypoint-initdb.d/init-mongo.js
    deploy:
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure

  mongo-express:
    image: mongo-express:latest
    env_file:
      - .env
    ports:
      - published: 8081
        target: 8081
        protocol: tcp
        mode: ingress
    networks:
      - default
      - backend
    deploy:
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure

  scraper:
    image: gdmurray/mma-oracle-scraper:latest
    env_file:
      - .env
    ports:
      - published: 3000
        target: 3000
        protocol: tcp
        mode: ingress
    networks:
      - backend
    deploy:
      replicas: 2
      update_config:
        order: start-first
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  backend:
    image: gdmurray/mma-oracle-backend:latest
    env_file:
      - .env
    ports:
      - published: 4000
        target: 4000
        protocol: tcp
        mode: ingress
    networks:
      - default
      - backend
    deploy:
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  odds-predictor:
    image: gdmurray/mma-oracle-odds-predictor:latest
    ports:
      - published: 5555
        target: 5555
        protocol: tcp
        mode: ingress
    networks:
      - backend
    env_file:
      - .env
    deploy:
      replicas: 1 # Default is 1, adjust based on your scaling needs
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

configs:
  init_mongo_script:
    file: ./scraper/init-mongo.js

volumes:
  mongodb_data_container:
  postgres_data_container:

networks:
  default:
  backend:
