name: Deploy Applications

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'odds-predictor/**'
      - 'scraper/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - backend
          - odds-predictor
          - scraper
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd ${{ matrix.app }}
          docker build -t mma-oracle/${{ matrix.app }}:latest .
          docker push mma-oracle/${{ matrix.app }}:latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: app
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Creating .env file..."
            
            # Create or overwrite an existing .env file with the environment variables
            cat > ~/mma-oracle/.env << EOF
            ME_CONFIG_BASICAUTH_PASSWORD=${{ secrets.ME_CONFIG_BASICAUTH_PASSWORD }}
            ME_CONFIG_BASICAUTH_USERNAME=${{ secrets.ME_CONFIG_BASICAUTH_USERNAME }}
            MONGODB_NAME=${{ secrets.MONGODB_NAME }}
            MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}
            MONGODB_USER=${{ secrets.MONGODB_USER }}
            MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
            MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            EOF
            
            echo ".env file created with secrets."
            
            cd ~/mma-oracle
            
            eval "$(ssh-agent -s)"
            ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"
            git pull origin main
            
            # Pull the latest images
            docker-compose -f docker-compose.prod.yml pull
            
            # Interpolate .env file and deploy the stack
            # The <(...) syntax creates a temporary file from the output of docker-compose config which docker stack deploy can use
            docker stack deploy -c <(docker-compose -f docker-compose.prod.yml config) mmaoracle
